version: '3.8'

services:
    cryptoaxus.redis:
        ports:
            - "6379:6379"
        expose:
            - "6379"

    cryptoaxus.api:
        image: armupdocker/cryptoaxus-armup-backend:latest
        environment:
            - ASPNETCORE_ENVIRONMENT=Staging
            - ASPNETCORE_URLS=http://+:80
        ports:
            - "6000:80"
            #- "5001:443"
        volumes:
            - ${APPDATA}\Microsoft\UserSecrets:\root\.microsoft\usersecrets:ro
            - ${APPDATA}\ASP.NET\Https:\root\.aspnet\https:ro