version: 2.1

orbs:
  windows: circleci/windows@5.0

jobs:
  build-and-test:
    executor:
      name: windows/default

    steps:
      - checkout
      - run:
          name: Restore
          command: dotnet restore
      - run:
          name: Build
          command: dotnet build
      - run:
          name: Running Tests
          command: dotnet test --no-build --verbosity normal

workflows:
  execute_pipeline:
    jobs:
      - build-and-test